title:              Legwork for Lungs
email:              info.legworkforlungs@gmail.com
description:        Racing to end lung cancer.
author:             Legwork for Lungs
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://legworkforlungs.github.io"

# Social Profiles
facebook_username:  legworkforlungs
instagram_username: legworkforlungs 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

collections:
  sponsors:
    output: true
    permalink: /past-sponsors/:name/
